// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SYS.Models;

namespace SYS.Migrations
{
    [DbContext(typeof(SysContext))]
    [Migration("20211114123718_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SYS.Models.Entities.SporcuBilgi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Boy")
                        .HasColumnType("int");

                    b.Property<string>("DogumTarihi")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DogumYeri")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EvAdresi")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("EvTelefon")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KanGrubu")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Kilo")
                        .HasColumnType("int");

                    b.Property<string>("OkuduguOkul")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Soyad")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("email")
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("SporcuBilgiler");
                });
#pragma warning restore 612, 618
        }
    }
}
